# Generated by Django 4.0.3 on 2022-03-31 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('order', models.IntegerField(help_text='The HEAD categories should have the lowest order numbers', verbose_name='Order in the category filter')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icon/')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category')),
            ],
        ),
    ]
