# Generated by Django 4.0.3 on 2022-04-01 16:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adpost_alter_category_options_adpostimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpost',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adpost',
            name='specifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='adpost',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
