# Generated by Django 4.0.3 on 2022-04-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_adpost_details_alter_adpost_specifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adpost',
            name='adpost_id',
        ),
        migrations.AddField(
            model_name='adpost',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='adpost',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
