# Generated by Django 4.0.3 on 2022-04-04 11:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_adpost_slug_alter_adpost_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('order', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon_name', models.CharField(max_length=30)),
                ('order', models.PositiveSmallIntegerField()),
                ('link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_header', models.ImageField(default='logo.png', upload_to='logo/')),
                ('logo_footer', models.ImageField(default='logo.png', upload_to='logo/')),
                ('website_name', models.CharField(max_length=100)),
                ('phone_main', models.CharField(max_length=20, verbose_name='Main Phone Number')),
                ('phone_support', models.CharField(blank=True, max_length=20, null=True, verbose_name='Support Number')),
                ('email_main', models.EmailField(max_length=254, verbose_name='Main Email Address')),
                ('email_support', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Support Email Address')),
                ('about_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('address', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_accounts', models.ManyToManyField(blank=True, to='core.socialaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('order', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_fields', to='core.headerfields')),
            ],
        ),
    ]
