# Generated by Django 4.0.3 on 2022-04-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_footerfields_socialaccounts_websitesettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialaccounts',
            options={'ordering': ['order']},
        ),
    ]
