# Generated by Django 4.0.3 on 2022-04-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_socialaccounts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerfields',
            options={'verbose_name_plural': 'Footer Fields'},
        ),
        migrations.AlterModelOptions(
            name='headerfields',
            options={'verbose_name_plural': 'Header Fields'},
        ),
        migrations.AlterModelOptions(
            name='socialaccounts',
            options={'ordering': ['order'], 'verbose_name_plural': 'Social Accounts'},
        ),
        migrations.AlterModelOptions(
            name='websitesettings',
            options={'verbose_name_plural': 'Website Settings'},
        ),
    ]
