# Generated by Django 4.0.3 on 2022-04-08 09:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_headerfields_parent'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='headerfields',
            managers=[
                ('status_filter', django.db.models.manager.Manager()),
            ],
        ),
    ]
