# Generated by Django 4.0.3 on 2022-04-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_headerfields_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='headerfields',
            managers=[
            ],
        ),
    ]
