# Generated by Django 4.0.3 on 2022-04-08 10:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_headerfields_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='footerfields',
            managers=[
                ('items', django.db.models.manager.Manager()),
            ],
        ),
    ]
