# Generated by Django 4.0.3 on 2022-04-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_footerfields_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='footerfields',
            managers=[
            ],
        ),
    ]
