# Generated by Django 4.0.3 on 2022-04-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_footerfields_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfields',
            name='is_footer',
            field=models.BooleanField(default=False),
        ),
    ]
