# Generated by Django 4.0.3 on 2022-04-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_headerfields_is_footer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterFields',
        ),
    ]
